/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Functions.Play4;

import Menu.FormMain;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author nguyentienthuan
 */
public class QuizzMonHocEnglish extends javax.swing.JPanel {

    /**
     * Creates new form QuizzVoice
     */
    public QuizzMonHocEnglish() {
        initComponents();
        btnextActionPerformed(null);
        bg.add(bt1);
        bg.add(bt2);
        bg.add(bt3);
        bg.add(bt4);

    }
    private static QuizzMonHocEnglish _instance;
    public static QuizzMonHocEnglish Instance() {
        if(_instance == null) 
            _instance = new QuizzMonHocEnglish();
        return _instance;
    }
    String[] question ={"Mathematics nghĩa là gì?", "Literature nghĩa là gì?","Foreign language nghĩa là gì?","History nghĩa là gì?","Physics nghĩa là gì?","Chemistry nghĩa là gì?"};
    String[][] option={{"Môn Toán","Ngoại Ngữ","Hóa học","Lịch Sử","Môn Toán"},{"Môn Toán","Ngoại Ngữ","Văn Học","Lịch Sử","Văn Học"},{"Môn Toán","Ngoại Ngữ","Hóa Học","Lịch Sử","Ngoại Ngữ"},{"Môn Toán","Vật Lý","Hóa học","Lịch Sử","Lịch Sử"},{"Môn Toán","Vật Lý","Hóa Học","Lịch Sử","Vật Lý"},{"Môn toán","Sinh Học","Hóa Học","Lịch Sử","Hóa Học"}};
    int index =0,correct=0;
    ButtonGroup bg = new ButtonGroup();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btback = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbques = new javax.swing.JLabel();
        btnext = new javax.swing.JButton();
        bt1 = new javax.swing.JRadioButton();
        bt2 = new javax.swing.JRadioButton();
        bt3 = new javax.swing.JRadioButton();
        bt4 = new javax.swing.JRadioButton();

        btback.setText("Back");
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lbques.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbques.setText("Question Here?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbques, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbques, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnext.setText("Câu hỏi tiếp theo");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        buttonGroup1.add(bt1);
        bt1.setText("jRadioButton1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(bt2);
        bt2.setText("jRadioButton2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(bt3);
        bt3.setText("jRadioButton3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(bt4);
        bt4.setText("jRadioButton4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btback)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt1)
                                    .addComponent(bt2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt4)
                                    .addComponent(bt3))
                                .addGap(31, 31, 31)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt2)
                    .addComponent(bt4))
                .addGap(30, 30, 30)
                .addComponent(btnext)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        // TODO add your handling code here:
        FormMain.Instance().setContentPane(PanelPlay4.Instance());
        FormMain.Instance().validate();
    }//GEN-LAST:event_btbackActionPerformed
    public void getSelectedOption(JRadioButton rdbt){
        if(rdbt.getText().equals(option[index][4])){
            correct++;
        }
        index++;
    }
    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        // TODO add your handling code here:
        if(btnext.getText().equals("Làm Lại")){
            btnext.setText("Câu hỏi tiếp theo");
            jPanel1.setBackground(new java.awt.Color(204,204,204));
            index=0;
            correct=0;
        }
        if(index==question.length){
            lbques.setText("Bạn được: "+correct+"/"+question.length);
            if(correct>=question.length/2){
                jPanel1.setBackground(Color.green);
            }
            else{
                jPanel1.setBackground(Color.RED);
            }
            btnext.setText("Làm Lại");
        }
        else {
        lbques.setText(question[index]);
        bt1.setText(option[index][0]);
        bt2.setText(option[index][1]);
        bt3.setText(option[index][2]);
        bt4.setText(option[index][3]);
        if(index==question.length-1)
            btnext.setText("Finish");
        }
        bg.clearSelection();

    }//GEN-LAST:event_btnextActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(bt1);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(bt2);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(bt3);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        getSelectedOption(bt4);
    }//GEN-LAST:event_bt4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bt1;
    private javax.swing.JRadioButton bt2;
    private javax.swing.JRadioButton bt3;
    private javax.swing.JRadioButton bt4;
    private javax.swing.JButton btback;
    private javax.swing.JButton btnext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbques;
    // End of variables declaration//GEN-END:variables
}
