/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Utils.Image.ImageUtils;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author chieu
 */
public class FormLogin extends javax.swing.JFrame {
    private boolean isDatabaseConnected = false;
    private static FormLogin _instance;
    public static FormLogin Instance() {
        if(_instance == null) {
            _instance = new FormLogin();
        }
        return _instance;
    }
    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        KetNoiCSDL();
        this.setResizable(false);
//        this.getContentPane().setBackground(new Color(209, 246, 246));
        ImageUtils.InitializeBackground((JPanel) this.getContentPane(), "login.png", 401, 318);
    }
    
    private Connection cnn;
    private void KetNoiCSDL() {
        cnn = Database.Database.KetNoiCSDL();
        if(cnn == null) {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối CSDL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            isDatabaseConnected = false;
        }
        else {
            isDatabaseConnected = true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnSkip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setPreferredSize(new java.awt.Dimension(401, 318));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TÊN ĐĂNG NHẬP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(67, 128, 130, 25);
        jLabel1.getAccessibleContext().setAccessibleName("lbUsername");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("MẬT KHẨU");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 171, 89, 25);
        jLabel2.getAccessibleContext().setAccessibleName("lbPassword");

        tfUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tfUsername);
        tfUsername.setBounds(205, 128, 129, 25);
        tfUsername.getAccessibleContext().setAccessibleName("tfUsername");

        tfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OnKeyEnterPress(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(205, 171, 129, 25);
        tfPassword.getAccessibleContext().setAccessibleName("tfPassword");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 2, 90));
        jLabel3.setText("English is Hard");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 47, 250, 48);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setText("Đăng nhập");
        btnLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnLoginClicked(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(67, 234, 116, 34);
        btnLogin.getAccessibleContext().setAccessibleName("btnLogin");

        btnSkip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSkip.setText("Bỏ qua");
        btnSkip.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        btnSkip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnSkipClick(evt);
            }
        });
        getContentPane().add(btnSkip);
        btnSkip.setBounds(231, 234, 103, 34);
        btnSkip.getAccessibleContext().setAccessibleName("btnSkip");

        getAccessibleContext().setAccessibleName("formLogin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnKeyEnterPress(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OnKeyEnterPress
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_OnKeyEnterPress

    private void OnLoginClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnLoginClicked
        // TODO add your handling code here:
        if(tfUsername.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Điền tên đăng nhập", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tfPassword.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Điền mật khẩu", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        KetNoiCSDL();
        String query = "SELECT * FROM users";
        try {
            PreparedStatement stm = cnn.prepareStatement(query);
            ResultSet rs = stm.executeQuery();
            while(rs.next()) {
                if(tfUsername.getText().equals(rs.getString("Username")) && 
                   tfPassword.getText().equals(rs.getString("Password"))) {
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");

                    User.Instance().setInfo(rs.getInt("UserID"),
                                            tfUsername.getText(),
                                            rs.getInt("Level"),
                                            rs.getInt("Exp"));
                    OnSkipClick(evt);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không chính xác!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Lỗi SQL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OnLoginClicked

    private void OnSkipClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnSkipClick
        // TODO add your handling code here:
//        if(!isDatabaseConnected) {
//            JOptionPane.showMessageDialog(this, "Không thể kết nối MySQL!", "Lỗi", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        Instance().setVisible(false);
        FormMain.Instance().setContentPane(PanelMenu.Instance());
        FormMain.Instance().validate();
        FormMain.Instance().setVisible(true);
    }//GEN-LAST:event_OnSkipClick


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Instance().setLocationRelativeTo(null);
                Instance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSkip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
